---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik
  namespace: kube-system
  labels:
    app: traefik-ingress-lb
spec:
  selector:
    matchLabels:
      app: traefik-ingress-lb
  template:
    metadata:
      labels:
        app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
      - image: traefik:v2.1.6
        name: traefik-ingress-lb
        ports:
        - name: web
          containerPort: 80
          hostPort: 80
        - name: websecure
          containerPort: 443
          hostPort: 443
        - name: admin
          containerPort: 8080
        - name: mongo
          hostPort: 27017
          containerPort: 27017
        - name: redis
          containerPort: 6379
          hostPort: 6379
        args:
        - --entrypoints.web.Address=:80
        - --entrypoints.websecure.Address=:443
        - --entryPoints.mongo.address=:27017
        - --entrypoints.redis.Address=:6379
        - --api.insecure=true
        - --providers.kubernetescrd
        - --api
        - --api.dashboard=true
        - --providers.kubernetesingress
        - --accesslog
        - --metrics
        - --metrics.datadog=true
        - --metrics.prometheus=true
        - --tracing
        - --tracing.zipkin=true
        
      nodeSelector:
        IngressProxy: "true"
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/ingress
        operator: Equal

---
kind: Service
apiVersion: v1
metadata:
  name: traefik
  namespace: kube-system
spec:
  type: ClusterIP
  selector:
    app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      name: web
      targetPort: 80
    - protocol: TCP
      port: 8080
      name: admin
      targetPort: 8080